#!/bin/bash
#first char 1, 2, 3, 4, 5, 6 or x all remotes
#2nd char  1, 2, 3, 4, 5, 6, 7, 8, 9 to to be defined.
 
mosquitto_pub  -h $1 -p 1883 -t 'pico/cmds' -u 'testuser' -P 'password123' -m '29hhmmss0a'
 
 
